name: Deploy VCN with GitHub OIDC to OCI UPST

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upst-terraform:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: "8aa264f421d646e98699b716b2e9b72e"
      CLIENT_SECRET: "idcscs-59183ab6-657c-4a24-ad24-ffae6c8bc061"
      DOMAIN_BASE_URL: "https://idcs-8dd307747946491cbfe1b7a3f063db0d.identity.oraclecloud.com"
      OCI_TENANCY: ${{ vars.OCI_TENANCY }}
      OCI_REGION: ${{ vars.OCI_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate RSA Key Pair
        run: |
          mkdir -p .oci
          openssl genrsa -out .oci/temp_private.pem 2048
          openssl rsa -in .oci/temp_private.pem -pubout -out .oci/temp_public.pem
          chmod 600 .oci/temp_private.pem .oci/temp_public.pem

     
