name: token_exchange

# Controls when the workflow will run
on:
  workflow_dispatch:
permissions:
  id-token: write       # REQUIRED to request OIDC token
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-oidc-token:
    runs-on: ubuntu-latest
    steps:
      - name: Request and Decode OIDC Token
        shell: bash
        run: |
          echo "Requesting OIDC token..."
          TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://oraclecloud.com/" \
            -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | jq -r '.value')

          echo "Decoding token payload (base64)..."
          echo "$TOKEN" | cut -d '.' -f2 | base64 -d | jq
          echo "full token"
          echo "$TOKEN"
